dataset:
  n_samples: 2000
  n_features: 20
  n_informative: 10
  n_classes: 2
  test_size: 0.2
  random_state: 42

models:
  LogisticRegression:
    C: [0.01, 0.1, 1.0, 10.0]
    max_iter: [100, 200, 500]

  RandomForestClassifier:
    n_estimators: [50, 100]
    max_depth: [5, 10, null]

  SVC:
    C: [0.1, 1, 10]
    kernel: ["linear", "rbf"]
